import { type TechStackData } from "@/types/techstack";

export const getTechStackData = (): TechStackData => {
  return {
    categories: [
      {
        id: "frameworks",
        name: "Frameworks",
        description: "Web and mobile development frameworks",
        color: [99, 102, 241],
        technologies: [
          {
            id: "laravel",
            name: "Laravel",
            icon: "Laravel",
            description: "A PHP web framework for building robust web applications",
            brandColor: "#FF2D20",
          },
          {
            id: "nextjs",
            name: "Next.js",
            icon: "Next.js",
            description: "The React framework for production",
            brandColor: "#000000",
          },
          {
            id: "bootstrap",
            name: "Bootstrap",
            icon: "Bootstrap",
            description: "A powerful, feature-packed frontend toolkit",
            brandColor: "#7952B3",
          },
          {
            id: "tailwindcss",
            name: "Tailwind CSS",
            icon: "Tailwind CSS",
            description: "A utility-first CSS framework for rapidly building custom designs",
            brandColor: "#38B2AC",
          },
          {
            id: "flutter",
            name: "Flutter",
            icon: "Flutter",
            description: "Google's UI toolkit for building natively compiled applications",
            brandColor: "#02569B",
          },
          {
            id: "nuxtjs",
            name: "Nuxt.js",
            icon: "Nuxt.js",
            description: "The intuitive Vue framework for building modern web applications",
            brandColor: "#00C58E",
          },
        ],
      },
      {
        id: "design-tools",
        name: "Design Tools",
        description: "Tools for UI/UX design and creative work",
        color: [236, 72, 153],
        technologies: [
          {
            id: "figma",
            name: "Figma",
            icon: "Figma",
            description: "A collaborative interface design tool",
            brandColor: "#F24E1E",
          },
          {
            id: "adobe-illustrator",
            name: "Adobe Illustrator",
            icon: "Adobe Illustrator",
            description: "Vector graphics software for creating logos, icons, and illustrations",
            brandColor: "#FF9A00",
          },
          {
            id: "adobe-photoshop",
            name: "Adobe Photoshop",
            icon: "Adobe Photoshop",
            description: "Image editing and graphic design software",
            brandColor: "#31A8FF",
          },
          {
            id: "adobe-premiere-pro",
            name: "Adobe Premiere Pro",
            icon: "Adobe Premiere Pro",
            description: "Industry-leading video editing software",
            brandColor: "#EA77FF",
          },
          {
            id: "adobe-audition",
            name: "Adobe Audition",
            icon: "Adobe Audition",
            description: "Digital audio workstation for audio editing and mixing",
            brandColor: "#9999FF",
          },
        ],
      },
      {
        id: "frontend",
        name: "Frontend",
        description: "Core technologies for client-side development",
        color: [34, 197, 94],
        technologies: [
          {
            id: "html",
            name: "HTML",
            icon: "HTML",
            description: "The latest version of Hypertext Markup Language",
            brandColor: "#E34F26",
          },
          {
            id: "css",
            name: "CSS",
            icon: "CSS",
            description: "The latest evolution of the Cascading Style Sheets language",
            brandColor: "#1572B6",
          },
          {
            id: "javascript",
            name: "JavaScript",
            icon: "JavaScript",
            description: "A high-level, often just-in-time compiled language",
            brandColor: "#F7DF1E",
          },
          {
            id: "sass",
            name: "Sass",
            icon: "Sass",
            description: "A preprocessor scripting language that is interpreted or compiled into CSS",
            brandColor: "#CC6699",
          },
          {
            id: "jquery",
            name: "jQuery",
            icon: "jQuery",
            description: "A fast, small, and feature-rich JavaScript library",
            brandColor: "#0769AD",
          },
          {
            id: "reactjs",
            name: "React.js",
            icon: "React.js",
            description: "A JavaScript library for building user interfaces",
            brandColor: "#61DAFB",
          },
          {
            id: "vuejs",
            name: "Vue.js",
            icon: "Vue.js",
            description: "A progressive JavaScript framework for building user interfaces",
            brandColor: "#4FC08D",
          },
          {
            id: "vite",
            name: "Vite",
            icon: "Vite",
            description: "A next-generation frontend tooling that provides an extremely fast development experience",
            brandColor: "#646CFF",
          },
        ],
      },
      {
        id: "backend",
        name: "Backend",
        description: "Server-side programming languages and technologies",
        color: [239, 68, 68],
        technologies: [
          {
            id: "php",
            name: "PHP",
            icon: "PHP",
            description: "A popular general-purpose scripting language for web development",
            brandColor: "#777BB4",
          },
          {
            id: "nodejs",
            name: "Node.js",
            icon: "Node.js",
            description: "A JavaScript runtime built on Chrome's V8 JavaScript engine",
            brandColor: "#339933",
          },
          {
            id: "python",
            name: "Python",
            icon: "Python",
            description: "An interpreted, high-level, general-purpose programming language",
            brandColor: "#3776AB",
          },
          {
            id: "java",
            name: "Java",
            icon: "Java",
            description: "A class-based, object-oriented programming language",
            brandColor: "#007396",
          },
          {
            id: "firebase",
            name: "Firebase",
            icon: "Firebase",
            description: "A platform developed by Google for creating mobile and web applications",
            brandColor: "#FFCA28",
          },
          {
            id: "golang",
            name: "Golang",
            icon: "Golang",
            description: "A statically typed, compiled programming language designed for simplicity and efficiency",
            brandColor: "#00ADD8",
          },
        ],
      },
      {
        id: "databases",
        name: "Databases",
        description: "Data storage and management systems",
        color: [168, 85, 247],
        technologies: [
          {
            id: "mysql",
            name: "MySQL",
            icon: "MySQL",
            description: "An open-source relational database management system",
            brandColor: "#4479A1",
          },
          {
            id: "mariadb",
            name: "MariaDB",
            icon: "MariaDB",
            description: "A community-developed, commercially supported fork of MySQL",
            brandColor: "#003545",
          },
          {
            id: "mongodb",
            name: "MongoDB",
            icon: "MongoDB",
            description: "A cross-platform document-oriented database program",
            brandColor: "#47A248",
          },
          {
            id: "postgresql",
            name: "PostgreSQL",
            icon: "PostgreSQL",
            description: "A powerful, open-source object-relational database system",
            brandColor: "#336791",
          },
          {
            id: "sqlite",
            name: "SQLite",
            icon: "SQLite",
            description: "A C-language library that implements a small, fast, self-contained SQL database engine",
            brandColor: "#003B57",
          },
        ],
      },
      {
        id: "others",
        name: "Others",
        description: "Miscellaneous tools and platforms",
        color: [16, 185, 129],
        technologies: [
          {
            id: "netlify",
            name: "Netlify",
            icon: "Netlify",
            description: "An all-in-one platform for automating web projects",
            brandColor: "#00C7B7",
          },
          {
            id: "vercel",
            name: "Vercel",
            icon: "Vercel",
            description: "The platform for frontend developers, providing speed and reliability",
            brandColor: "#000000",
          },
        ],
      },
    ],
  };
};

